### ISSUE TITLE
Error: Parameter "key" is required

### ISSUE THREAD

**Issue by preet1312** [theoomoregbee/US-visa-appointment-notifier#14]
Error: Parameter "key" is required
    at new _ (C:\US-visa-appointment-notifier-main\node_modules\mailgun.js\mailgun.node.js:2:32862)
    at e.client (C:\US-visa-appointment-notifier-main\node_modules\mailgun.js\mailgun.node.js:2:58416)
    at Object.<anonymous> (C:\US-visa-appointment-notifier-main\utils.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\US-visa-appointment-notifier-main\index.js:4:37)

Appreciate if anyone can assist on priority pls.

**Comment by theoomoregbee** [comment]
You need to create a mailgun acount to get the mailgun key. See readme mailgun section and also configuration
