### ISSUE TITLE
Process Timeout

### ISSUE THREAD

**Issue by muserxu** [theoomoregbee/US-visa-appointment-notifier#18]
I set the process to have a large number of tries (10000) but the app will shut down after some time ~2000 tries with below error message

```
Error: net::ERR_EMPTY_RESPONSE at https://ais.usvisa-info.com/en-ca/niv/schedule/46436140/appointment/days/94.json?appointments%5Bexpedite%5D=false
    at navigate (/workplace/XXX/US-visa-appointment-notifier/node_modules/puppeteer/lib/cjs/puppeteer/common/Frame.js:199:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Frame.goto (/workplace/XXX/US-visa-appointment-notifier/node_modules/puppeteer/lib/cjs/puppeteer/common/Frame.js:169:21)
    at async Page.goto (/workplace/XXX/US-visa-appointment-notifier/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1144:16)
    at async checkForSchedules (/workplace/XXX/US-visa-appointment-notifier/index.js:43:3)
    at async process (/workplace/XXX/US-visa-appointment-notifier/index.js:84:24)
    at async process (/workplace/XXX/US-visa-appointment-notifier/index.js:91:3)
    at async process (/workplace/XXX/US-visa-appointment-notifier/index.js:91:3)
    at async process (/workplace/XXX/US-visa-appointment-notifier/index.js:91:3)
    at async process (/workplace/XXX/US-visa-appointment-notifier/index.js:9
```

**Comment by theoomoregbee** [comment]
This is from the website not the script.
