### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by LacinaSilue** [theoomoregbee/US-visa-appointment-notifier#34]
Hello ! Thanks for your application. But I do not know why I get this error anytime I run it. 

TimeoutError: Navigation timeout of 30000 ms exceeded
    at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (C:\Users\Labex\US-visa-appointment-notifier\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:164:12)
    at async Frame.waitForNavigation (C:\Users\Labex\US-visa-appointment-notifier\node_modules\puppeteer\lib\cjs\puppeteer\common\Frame.js:236:23)
    at async Page.waitForNavigation (C:\Users\Labex\US-visa-appointment-notifier\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1207:16)
    at async login (C:\Users\Labex\US-visa-appointment-notifier\index.js:27:3)
    at async process (C:\Users\Labex\US-visa-appointment-notifier\index.js:85:19)
    at async C:\Users\Labex\US-visa-appointment-notifier\index.js:103:5

**Comment by KeeratKG** [comment]
Hi. 
I experienced a similar issue, and finally resolved it by fixing my saved version of puppeteer as suggested [here](https://stackoverflow.com/questions/53764902/cannot-find-module-puppeteer). 

Run the following command in the repo location: `npm i puppeteer --save`

Versions: 
```
> npm -v

9.5.1

> node -v

v18.16.0
```

Hope this helps!
