### ISSUE TITLE
Error: Parameter "key" is required

### ISSUE THREAD

**Issue by zehao-ba** [theoomoregbee/US-visa-appointment-notifier#40]
Hello, i am having this error when i run 'npm start':

Error: Parameter "key" is required
at new _ (/Users/xxx/Desktop/US-visa-appointment-notifier-main/node_modules/mailgun.js/mailgun.node.js:2:32862)
at e.client (/Users/xxx/Desktop/US-visa-appointment-notifier-main/node_modules/mailgun.js/mailgun.node.js:2:58416)
at Object. (/Users/xxx/Desktop/US-visa-appointment-notifier-main/utils.js:6:20)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Module._load (node:internal/modules/cjs/loader:1023:12)
at Module.require (node:internal/modules/cjs/loader:1235:19)
at require (node:internal/modules/helpers:176:18)
at Object. (/Users/xxx/Desktop/US-visa-appointment-notifier-main/index.js:5:37)

My env is setting as:
NOTIFY_EMAILS='[email@gmail.com](mailto:email@gmail.com)'
MAILGUN_USERNAME='[email@gmail.com](mailto:email@gmail.com)'
MAILGUN_DOMAIN='sandboxaxxxx.mailgun.org'
MAILGUN_API_KEY='pubkey-xxxx'

Browsing other solution but still doesn't help :(

**Comment by jyotsana-s** [comment]
Seems like the code is not able to find your API KEY. Change filename from .env.example to .env and try

**Comment by siddharthrawal121** [comment]
@zehao-ba did you found what the problem is?
